from fastapi_mail import ConnectionConfig

from app.config import (
    MAIL_USERNAME,
    MAIL_PASSWORD,
    MAIL_FROM,
    MAIL_PORT,
    MAIL_SERVER,
    MAIL_FROM_NAME,
    MAIL_STARTTLS,
    MAIL_SSL_TLS
)

conf = ConnectionConfig(

    MAIL_USERNAME=MAIL_USERNAME,

    MAIL_PASSWORD=MAIL_PASSWORD,

    MAIL_FROM=MAIL_FROM,

    MAIL_PORT=MAIL_PORT,

    MAIL_SERVER=MAIL_SERVER,

    MAIL_FROM_NAME=MAIL_FROM_NAME,

    MAIL_STARTTLS=MAIL_STARTTLS,

    MAIL_SSL_TLS=MAIL_SSL_TLS,

    USE_CREDENTIALS=True

)